// List of disposable email domains to reject
export const disposableDomains = [
  '10minutemail.com',
  'guerrillamail.com',
  'mailinator.com',
  'tempmail.org',
  'throwaway.email',
  'yopmail.com',
  'temp-mail.org',
  'sharklasers.com',
  'grr.la',
  'guerrillamailblock.com',
  'pokemail.net',
  'spam4.me',
  'bccto.me',
  'chacuo.net',
  'dispostable.com',
  'mailnesia.com',
  'maildrop.cc',
  'mailcatch.com',
  'inboxalias.com',
  'getairmail.com',
  'mintemail.com',
  'spamgourmet.com',
  'spammotel.com',
  'spamspot.com',
  'spam.la',
  'noclickemail.com',
  'mailnull.com',
  'spamfree24.org',
  'spamfree24.com',
  'spamfree24.net',
  'spamfree24.de',
  'spam4.me',
  'bccto.me',
  'chacuo.net',
  'dispostable.com',
  'mailnesia.com',
  'maildrop.cc',
  'mailcatch.com',
  'inboxalias.com',
  'getairmail.com',
  'mintemail.com',
  'spamgourmet.com',
  'spammotel.com',
  'spamspot.com',
  'spam.la',
  'noclickemail.com',
  'mailnull.com',
  'spamfree24.org',
  'spamfree24.com',
  'spamfree24.net',
  'spamfree24.de'
];

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase();
  return domain ? disposableDomains.includes(domain) : false;
}
